
name: Demo

on:
  # webhook event
  push:
    branches: 
      - main
      - Task/*
      - feat/*
  pull_request:
    branches:
      - main
 
  # schedule event
  schedule:
    - cron: 0 12 * * *
    - cron: 0 9 * * 0 
  workflow_dispatch: # for manual events
    inputs:
      areYouFeelingGood:
        description: "Are you feeling good?"
        type: boolean
        default: false

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from Github Actions !"

  Job2:
    runs-on: ubuntu-latest
    needs: [Job1]
    steps:
      - name: Step2
        run: echo " This is Step2 with needs of Job1"

      - name: Step3
        if: ${{ inputs.areYouFeelingGood }}
        run: echo "Great!"

      - name: Step4
        if: ${{ !inputs.areYouFeelingGood }}
        run: echo "Not feeling good?"
