
name: Demo

on:
  workflow_dispatch:
    inputs:
      areYouFeelingGood:
        description: "Are you feeling good?"
        type: boolean
        default: false

jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from Greeting!"

  Job2:
    runs-on: ubuntu-latest
    needs: [Greeting]
    steps:
      - name: Step2
        run: echo "${{ github.actor }} is learning GitHub Actions."

      - name: Step3
        if: ${{ inputs.areYouFeelingGood }}
        run: echo "Great!"

      - name: Step4
        if: ${{ !inputs.areYouFeelingGood }}
        run: echo "No worries, I am here with you!"
