
name: Demo

on:
  workflow_dispatch:
    inputs:
      areYouFeelingGood:
        description: "Are you feeling good?"
        type: boolean
        default: false

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from Github Actions !"

  Job2:
    runs-on: ubuntu-latest
    needs: [Job1]
    steps:
      - name: Step2
        run: echo " This is Step2 with needs of Job1"

      - name: Step3
        if: ${{ inputs.areYouFeelingGood }}
        run: echo "Great!"

      - name: Step4
        if: ${{ !inputs.areYouFeelingGood }}
        run: echo "Not feeling good?"
