name : Environment Variables

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Select the target environment'
        type: choice
        options:
          - Staging
          - Production
          - Testing
        default: Testing

      user_name:
        description: 'Enter your name'
        type: string
        required: true
        default: 'Guest'

jobs:
  print_env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    steps:
      - name:  Show Selected Environment
        run: |
          echo "Selected Environment: ${{ inputs.target_env }}"

      - name: Display Message
        run: |
          echo "Hello, ${{ inputs.user_name }}!"
          echo "${{vars.ENV_GREETING}} from the ${{ inputs.target_env }} environment!"
      
  