name: YAML Linting

on:
  push:
    paths: ['**/*.yaml', '**/*.yml']
  pull_request:
    paths: ['**/*.yaml', '**/*.yml']
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install & Run yamllint
        run: |
          set -e
          pip install yamllint
          yamllint -f colored -s .